/*
 * Midjourney api-unofficial by Legnext.ai
 * # **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ApiV1JobJobIdGet200ResponseOutputAvailableActions
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T18:54:28.851432016+08:00[Asia/Shanghai]", comments = "Generator version: 7.18.0")
public class ApiV1JobJobIdGet200ResponseOutputAvailableActions {
  public static final String SERIALIZED_NAME_EDIT = "edit";
  @SerializedName(SERIALIZED_NAME_EDIT)
  @javax.annotation.Nullable
  private List<Integer> edit = new ArrayList<>();

  public static final String SERIALIZED_NAME_INPAINT = "inpaint";
  @SerializedName(SERIALIZED_NAME_INPAINT)
  @javax.annotation.Nullable
  private List<Integer> inpaint = new ArrayList<>();

  public static final String SERIALIZED_NAME_OUTPAINT = "outpaint";
  @SerializedName(SERIALIZED_NAME_OUTPAINT)
  @javax.annotation.Nullable
  private List<Integer> outpaint = new ArrayList<>();

  public static final String SERIALIZED_NAME_PAN = "pan";
  @SerializedName(SERIALIZED_NAME_PAN)
  @javax.annotation.Nullable
  private List<Integer> pan = new ArrayList<>();

  public static final String SERIALIZED_NAME_REMIX = "remix";
  @SerializedName(SERIALIZED_NAME_REMIX)
  @javax.annotation.Nullable
  private List<Integer> remix = new ArrayList<>();

  public static final String SERIALIZED_NAME_REROLL = "reroll";
  @SerializedName(SERIALIZED_NAME_REROLL)
  @javax.annotation.Nullable
  private Boolean reroll;

  public static final String SERIALIZED_NAME_UPSCALE = "upscale";
  @SerializedName(SERIALIZED_NAME_UPSCALE)
  @javax.annotation.Nullable
  private List<Integer> upscale = new ArrayList<>();

  public static final String SERIALIZED_NAME_VARIATION = "variation";
  @SerializedName(SERIALIZED_NAME_VARIATION)
  @javax.annotation.Nullable
  private List<Integer> variation = new ArrayList<>();

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions() {
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions edit(@javax.annotation.Nullable List<Integer> edit) {
    this.edit = edit;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addEditItem(Integer editItem) {
    if (this.edit == null) {
      this.edit = new ArrayList<>();
    }
    this.edit.add(editItem);
    return this;
  }

  /**
   * Get edit
   * @return edit
   */
  @javax.annotation.Nullable
  public List<Integer> getEdit() {
    return edit;
  }

  public void setEdit(@javax.annotation.Nullable List<Integer> edit) {
    this.edit = edit;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions inpaint(@javax.annotation.Nullable List<Integer> inpaint) {
    this.inpaint = inpaint;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addInpaintItem(Integer inpaintItem) {
    if (this.inpaint == null) {
      this.inpaint = new ArrayList<>();
    }
    this.inpaint.add(inpaintItem);
    return this;
  }

  /**
   * Get inpaint
   * @return inpaint
   */
  @javax.annotation.Nullable
  public List<Integer> getInpaint() {
    return inpaint;
  }

  public void setInpaint(@javax.annotation.Nullable List<Integer> inpaint) {
    this.inpaint = inpaint;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions outpaint(@javax.annotation.Nullable List<Integer> outpaint) {
    this.outpaint = outpaint;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addOutpaintItem(Integer outpaintItem) {
    if (this.outpaint == null) {
      this.outpaint = new ArrayList<>();
    }
    this.outpaint.add(outpaintItem);
    return this;
  }

  /**
   * Get outpaint
   * @return outpaint
   */
  @javax.annotation.Nullable
  public List<Integer> getOutpaint() {
    return outpaint;
  }

  public void setOutpaint(@javax.annotation.Nullable List<Integer> outpaint) {
    this.outpaint = outpaint;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions pan(@javax.annotation.Nullable List<Integer> pan) {
    this.pan = pan;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addPanItem(Integer panItem) {
    if (this.pan == null) {
      this.pan = new ArrayList<>();
    }
    this.pan.add(panItem);
    return this;
  }

  /**
   * Get pan
   * @return pan
   */
  @javax.annotation.Nullable
  public List<Integer> getPan() {
    return pan;
  }

  public void setPan(@javax.annotation.Nullable List<Integer> pan) {
    this.pan = pan;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions remix(@javax.annotation.Nullable List<Integer> remix) {
    this.remix = remix;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addRemixItem(Integer remixItem) {
    if (this.remix == null) {
      this.remix = new ArrayList<>();
    }
    this.remix.add(remixItem);
    return this;
  }

  /**
   * Get remix
   * @return remix
   */
  @javax.annotation.Nullable
  public List<Integer> getRemix() {
    return remix;
  }

  public void setRemix(@javax.annotation.Nullable List<Integer> remix) {
    this.remix = remix;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions reroll(@javax.annotation.Nullable Boolean reroll) {
    this.reroll = reroll;
    return this;
  }

  /**
   * Get reroll
   * @return reroll
   */
  @javax.annotation.Nullable
  public Boolean getReroll() {
    return reroll;
  }

  public void setReroll(@javax.annotation.Nullable Boolean reroll) {
    this.reroll = reroll;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions upscale(@javax.annotation.Nullable List<Integer> upscale) {
    this.upscale = upscale;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addUpscaleItem(Integer upscaleItem) {
    if (this.upscale == null) {
      this.upscale = new ArrayList<>();
    }
    this.upscale.add(upscaleItem);
    return this;
  }

  /**
   * Get upscale
   * @return upscale
   */
  @javax.annotation.Nullable
  public List<Integer> getUpscale() {
    return upscale;
  }

  public void setUpscale(@javax.annotation.Nullable List<Integer> upscale) {
    this.upscale = upscale;
  }


  public ApiV1JobJobIdGet200ResponseOutputAvailableActions variation(@javax.annotation.Nullable List<Integer> variation) {
    this.variation = variation;
    return this;
  }

  public ApiV1JobJobIdGet200ResponseOutputAvailableActions addVariationItem(Integer variationItem) {
    if (this.variation == null) {
      this.variation = new ArrayList<>();
    }
    this.variation.add(variationItem);
    return this;
  }

  /**
   * Get variation
   * @return variation
   */
  @javax.annotation.Nullable
  public List<Integer> getVariation() {
    return variation;
  }

  public void setVariation(@javax.annotation.Nullable List<Integer> variation) {
    this.variation = variation;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV1JobJobIdGet200ResponseOutputAvailableActions apiV1JobJobIdGet200ResponseOutputAvailableActions = (ApiV1JobJobIdGet200ResponseOutputAvailableActions) o;
    return Objects.equals(this.edit, apiV1JobJobIdGet200ResponseOutputAvailableActions.edit) &&
        Objects.equals(this.inpaint, apiV1JobJobIdGet200ResponseOutputAvailableActions.inpaint) &&
        Objects.equals(this.outpaint, apiV1JobJobIdGet200ResponseOutputAvailableActions.outpaint) &&
        Objects.equals(this.pan, apiV1JobJobIdGet200ResponseOutputAvailableActions.pan) &&
        Objects.equals(this.remix, apiV1JobJobIdGet200ResponseOutputAvailableActions.remix) &&
        Objects.equals(this.reroll, apiV1JobJobIdGet200ResponseOutputAvailableActions.reroll) &&
        Objects.equals(this.upscale, apiV1JobJobIdGet200ResponseOutputAvailableActions.upscale) &&
        Objects.equals(this.variation, apiV1JobJobIdGet200ResponseOutputAvailableActions.variation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(edit, inpaint, outpaint, pan, remix, reroll, upscale, variation);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV1JobJobIdGet200ResponseOutputAvailableActions {\n");
    sb.append("    edit: ").append(toIndentedString(edit)).append("\n");
    sb.append("    inpaint: ").append(toIndentedString(inpaint)).append("\n");
    sb.append("    outpaint: ").append(toIndentedString(outpaint)).append("\n");
    sb.append("    pan: ").append(toIndentedString(pan)).append("\n");
    sb.append("    remix: ").append(toIndentedString(remix)).append("\n");
    sb.append("    reroll: ").append(toIndentedString(reroll)).append("\n");
    sb.append("    upscale: ").append(toIndentedString(upscale)).append("\n");
    sb.append("    variation: ").append(toIndentedString(variation)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("edit", "inpaint", "outpaint", "pan", "remix", "reroll", "upscale", "variation"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ApiV1JobJobIdGet200ResponseOutputAvailableActions
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiV1JobJobIdGet200ResponseOutputAvailableActions.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ApiV1JobJobIdGet200ResponseOutputAvailableActions is not found in the empty JSON string", ApiV1JobJobIdGet200ResponseOutputAvailableActions.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApiV1JobJobIdGet200ResponseOutputAvailableActions.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ApiV1JobJobIdGet200ResponseOutputAvailableActions` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // ensure the optional json data is an array if present
      if (jsonObj.get("edit") != null && !jsonObj.get("edit").isJsonNull() && !jsonObj.get("edit").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `edit` to be an array in the JSON string but got `%s`", jsonObj.get("edit").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("inpaint") != null && !jsonObj.get("inpaint").isJsonNull() && !jsonObj.get("inpaint").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `inpaint` to be an array in the JSON string but got `%s`", jsonObj.get("inpaint").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("outpaint") != null && !jsonObj.get("outpaint").isJsonNull() && !jsonObj.get("outpaint").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `outpaint` to be an array in the JSON string but got `%s`", jsonObj.get("outpaint").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("pan") != null && !jsonObj.get("pan").isJsonNull() && !jsonObj.get("pan").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `pan` to be an array in the JSON string but got `%s`", jsonObj.get("pan").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("remix") != null && !jsonObj.get("remix").isJsonNull() && !jsonObj.get("remix").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `remix` to be an array in the JSON string but got `%s`", jsonObj.get("remix").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("upscale") != null && !jsonObj.get("upscale").isJsonNull() && !jsonObj.get("upscale").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `upscale` to be an array in the JSON string but got `%s`", jsonObj.get("upscale").toString()));
      }
      // ensure the optional json data is an array if present
      if (jsonObj.get("variation") != null && !jsonObj.get("variation").isJsonNull() && !jsonObj.get("variation").isJsonArray()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `variation` to be an array in the JSON string but got `%s`", jsonObj.get("variation").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiV1JobJobIdGet200ResponseOutputAvailableActions.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiV1JobJobIdGet200ResponseOutputAvailableActions' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiV1JobJobIdGet200ResponseOutputAvailableActions> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiV1JobJobIdGet200ResponseOutputAvailableActions.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiV1JobJobIdGet200ResponseOutputAvailableActions>() {
           @Override
           public void write(JsonWriter out, ApiV1JobJobIdGet200ResponseOutputAvailableActions value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiV1JobJobIdGet200ResponseOutputAvailableActions read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ApiV1JobJobIdGet200ResponseOutputAvailableActions given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ApiV1JobJobIdGet200ResponseOutputAvailableActions
   * @throws IOException if the JSON string is invalid with respect to ApiV1JobJobIdGet200ResponseOutputAvailableActions
   */
  public static ApiV1JobJobIdGet200ResponseOutputAvailableActions fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiV1JobJobIdGet200ResponseOutputAvailableActions.class);
  }

  /**
   * Convert an instance of ApiV1JobJobIdGet200ResponseOutputAvailableActions to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

