/*
 * Midjourney api-unofficial by Legnext.ai
 * # **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * ApiV1DiffusionPost200ResponseMetaUsage
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-01-13T18:54:28.851432016+08:00[Asia/Shanghai]", comments = "Generator version: 7.18.0")
public class ApiV1DiffusionPost200ResponseMetaUsage {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  @javax.annotation.Nullable
  private String type;

  public static final String SERIALIZED_NAME_FROZEN = "frozen";
  @SerializedName(SERIALIZED_NAME_FROZEN)
  @javax.annotation.Nullable
  private Integer frozen;

  public static final String SERIALIZED_NAME_CONSUME = "consume";
  @SerializedName(SERIALIZED_NAME_CONSUME)
  @javax.annotation.Nullable
  private Integer consume;

  public ApiV1DiffusionPost200ResponseMetaUsage() {
  }

  public ApiV1DiffusionPost200ResponseMetaUsage type(@javax.annotation.Nullable String type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }

  public void setType(@javax.annotation.Nullable String type) {
    this.type = type;
  }


  public ApiV1DiffusionPost200ResponseMetaUsage frozen(@javax.annotation.Nullable Integer frozen) {
    this.frozen = frozen;
    return this;
  }

  /**
   * Get frozen
   * @return frozen
   */
  @javax.annotation.Nullable
  public Integer getFrozen() {
    return frozen;
  }

  public void setFrozen(@javax.annotation.Nullable Integer frozen) {
    this.frozen = frozen;
  }


  public ApiV1DiffusionPost200ResponseMetaUsage consume(@javax.annotation.Nullable Integer consume) {
    this.consume = consume;
    return this;
  }

  /**
   * Get consume
   * @return consume
   */
  @javax.annotation.Nullable
  public Integer getConsume() {
    return consume;
  }

  public void setConsume(@javax.annotation.Nullable Integer consume) {
    this.consume = consume;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiV1DiffusionPost200ResponseMetaUsage apiV1DiffusionPost200ResponseMetaUsage = (ApiV1DiffusionPost200ResponseMetaUsage) o;
    return Objects.equals(this.type, apiV1DiffusionPost200ResponseMetaUsage.type) &&
        Objects.equals(this.frozen, apiV1DiffusionPost200ResponseMetaUsage.frozen) &&
        Objects.equals(this.consume, apiV1DiffusionPost200ResponseMetaUsage.consume);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, frozen, consume);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiV1DiffusionPost200ResponseMetaUsage {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    frozen: ").append(toIndentedString(frozen)).append("\n");
    sb.append("    consume: ").append(toIndentedString(consume)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>(Arrays.asList("type", "frozen", "consume"));

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>(0);
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to ApiV1DiffusionPost200ResponseMetaUsage
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!ApiV1DiffusionPost200ResponseMetaUsage.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The required field(s) %s in ApiV1DiffusionPost200ResponseMetaUsage is not found in the empty JSON string", ApiV1DiffusionPost200ResponseMetaUsage.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!ApiV1DiffusionPost200ResponseMetaUsage.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "The field `%s` in the JSON string is not defined in the `ApiV1DiffusionPost200ResponseMetaUsage` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format(java.util.Locale.ROOT, "Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!ApiV1DiffusionPost200ResponseMetaUsage.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'ApiV1DiffusionPost200ResponseMetaUsage' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<ApiV1DiffusionPost200ResponseMetaUsage> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(ApiV1DiffusionPost200ResponseMetaUsage.class));

       return (TypeAdapter<T>) new TypeAdapter<ApiV1DiffusionPost200ResponseMetaUsage>() {
           @Override
           public void write(JsonWriter out, ApiV1DiffusionPost200ResponseMetaUsage value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public ApiV1DiffusionPost200ResponseMetaUsage read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of ApiV1DiffusionPost200ResponseMetaUsage given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of ApiV1DiffusionPost200ResponseMetaUsage
   * @throws IOException if the JSON string is invalid with respect to ApiV1DiffusionPost200ResponseMetaUsage
   */
  public static ApiV1DiffusionPost200ResponseMetaUsage fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, ApiV1DiffusionPost200ResponseMetaUsage.class);
  }

  /**
   * Convert an instance of ApiV1DiffusionPost200ResponseMetaUsage to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

