=begin
#Midjourney api-unofficial by Legnext.ai

## **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.

The version of the OpenAPI document: 1.0.0

Generated by: https://openapi-generator.tech
Generator version: 7.18.0

=end

require 'spec_helper'
require 'json'

# Unit tests for OpenapiClient::AccountManagementApi
# Automatically generated by openapi-generator (https://openapi-generator.tech)
# Please update as you see appropriate
describe 'AccountManagementApi' do
  before do
    # run before each test
    @api_instance = OpenapiClient::AccountManagementApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountManagementApi' do
    it 'should create an instance of AccountManagementApi' do
      expect(@api_instance).to be_instance_of(OpenapiClient::AccountManagementApi)
    end
  end

  # unit tests for api_account_balance_get
  # get account balance
  # ## Retrieve Account Balance and Credit Information  Get your current account balance, available credits, points, and low balance alert settings. Essential for monitoring usage and managing costs.  ### How it Works  Make a GET request to retrieve current account status. The API returns real-time balance information, available credits for API usage, and alert settings.  ### Required Parameters  None - this is a simple GET request with authentication  ### Authentication  Requires a valid API key passed in the &#x60;x-api-key&#x60; header (note: some implementations use &#x60;X-API-KEY&#x60;).  ### Response  Returns account balance information including:  - &#x60;account_id&#x60; - Your account identifier      - &#x60;balance_usd&#x60; - Current balance in USD      - &#x60;available_credits&#x60; - Credits available for API usage      - &#x60;available_points&#x60; - Points balance      - &#x60;alert_threshold&#x60; - Low balance alert threshold (USD)      - &#x60;low_balance_alert&#x60; - Whether low balance alert is triggered      - &#x60;updated_at&#x60; - Last update timestamp       ### Use Cases  - Monitor remaining credits before large batch operations      - Set up automated balance monitoring in applications      - Verify successful credit purchases or additions      - Track usage and spending over time      - Implement low-balance warnings in applications       ### Tips  - Check balance before large batch operations to avoid interruptions      - Balance is in USD, credits are usage tokens      - Low balance alert threshold can be configured in dashboard      - Updated in real-time - reflects immediate usage      - Use for cost monitoring and budget management
  # @param [Hash] opts the optional parameters
  # @option opts [String] :x_api_key 
  # @return [BalanceResponse]
  describe 'api_account_balance_get test' do
    it 'should work' do
      # assertion here. ref: https://rspec.info/features/3-12/rspec-expectations/built-in-matchers/
    end
  end

end
