/*
Midjourney api-unofficial by Legnext.ai

# **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package legnext

import (
	"encoding/json"
)

// checks if the ApiV1DiffusionPost200ResponseMetaUsage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1DiffusionPost200ResponseMetaUsage{}

// ApiV1DiffusionPost200ResponseMetaUsage struct for ApiV1DiffusionPost200ResponseMetaUsage
type ApiV1DiffusionPost200ResponseMetaUsage struct {
	Type *string `json:"type,omitempty"`
	Frozen *int32 `json:"frozen,omitempty"`
	Consume *int32 `json:"consume,omitempty"`
}

// NewApiV1DiffusionPost200ResponseMetaUsage instantiates a new ApiV1DiffusionPost200ResponseMetaUsage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1DiffusionPost200ResponseMetaUsage() *ApiV1DiffusionPost200ResponseMetaUsage {
	this := ApiV1DiffusionPost200ResponseMetaUsage{}
	return &this
}

// NewApiV1DiffusionPost200ResponseMetaUsageWithDefaults instantiates a new ApiV1DiffusionPost200ResponseMetaUsage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1DiffusionPost200ResponseMetaUsageWithDefaults() *ApiV1DiffusionPost200ResponseMetaUsage {
	this := ApiV1DiffusionPost200ResponseMetaUsage{}
	return &this
}

// GetType returns the Type field value if set, zero value otherwise.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) GetType() string {
	if o == nil || IsNil(o.Type) {
		var ret string
		return ret
	}
	return *o.Type
}

// GetTypeOk returns a tuple with the Type field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) GetTypeOk() (*string, bool) {
	if o == nil || IsNil(o.Type) {
		return nil, false
	}
	return o.Type, true
}

// HasType returns a boolean if a field has been set.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) HasType() bool {
	if o != nil && !IsNil(o.Type) {
		return true
	}

	return false
}

// SetType gets a reference to the given string and assigns it to the Type field.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) SetType(v string) {
	o.Type = &v
}

// GetFrozen returns the Frozen field value if set, zero value otherwise.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) GetFrozen() int32 {
	if o == nil || IsNil(o.Frozen) {
		var ret int32
		return ret
	}
	return *o.Frozen
}

// GetFrozenOk returns a tuple with the Frozen field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) GetFrozenOk() (*int32, bool) {
	if o == nil || IsNil(o.Frozen) {
		return nil, false
	}
	return o.Frozen, true
}

// HasFrozen returns a boolean if a field has been set.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) HasFrozen() bool {
	if o != nil && !IsNil(o.Frozen) {
		return true
	}

	return false
}

// SetFrozen gets a reference to the given int32 and assigns it to the Frozen field.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) SetFrozen(v int32) {
	o.Frozen = &v
}

// GetConsume returns the Consume field value if set, zero value otherwise.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) GetConsume() int32 {
	if o == nil || IsNil(o.Consume) {
		var ret int32
		return ret
	}
	return *o.Consume
}

// GetConsumeOk returns a tuple with the Consume field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) GetConsumeOk() (*int32, bool) {
	if o == nil || IsNil(o.Consume) {
		return nil, false
	}
	return o.Consume, true
}

// HasConsume returns a boolean if a field has been set.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) HasConsume() bool {
	if o != nil && !IsNil(o.Consume) {
		return true
	}

	return false
}

// SetConsume gets a reference to the given int32 and assigns it to the Consume field.
func (o *ApiV1DiffusionPost200ResponseMetaUsage) SetConsume(v int32) {
	o.Consume = &v
}

func (o ApiV1DiffusionPost200ResponseMetaUsage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1DiffusionPost200ResponseMetaUsage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Type) {
		toSerialize["type"] = o.Type
	}
	if !IsNil(o.Frozen) {
		toSerialize["frozen"] = o.Frozen
	}
	if !IsNil(o.Consume) {
		toSerialize["consume"] = o.Consume
	}
	return toSerialize, nil
}

type NullableApiV1DiffusionPost200ResponseMetaUsage struct {
	value *ApiV1DiffusionPost200ResponseMetaUsage
	isSet bool
}

func (v NullableApiV1DiffusionPost200ResponseMetaUsage) Get() *ApiV1DiffusionPost200ResponseMetaUsage {
	return v.value
}

func (v *NullableApiV1DiffusionPost200ResponseMetaUsage) Set(val *ApiV1DiffusionPost200ResponseMetaUsage) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1DiffusionPost200ResponseMetaUsage) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1DiffusionPost200ResponseMetaUsage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1DiffusionPost200ResponseMetaUsage(val *ApiV1DiffusionPost200ResponseMetaUsage) *NullableApiV1DiffusionPost200ResponseMetaUsage {
	return &NullableApiV1DiffusionPost200ResponseMetaUsage{value: val, isSet: true}
}

func (v NullableApiV1DiffusionPost200ResponseMetaUsage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1DiffusionPost200ResponseMetaUsage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


