/*
Midjourney api-unofficial by Legnext.ai

# **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package legnext

import (
	"encoding/json"
	"time"
)

// checks if the ApiV1JobJobIdGet200ResponseMeta type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1JobJobIdGet200ResponseMeta{}

// ApiV1JobJobIdGet200ResponseMeta struct for ApiV1JobJobIdGet200ResponseMeta
type ApiV1JobJobIdGet200ResponseMeta struct {
	CreatedAt *time.Time `json:"created_at,omitempty"`
	StartedAt *time.Time `json:"started_at,omitempty"`
	EndedAt *time.Time `json:"ended_at,omitempty"`
	Usage *ApiV1DiffusionPost200ResponseMetaUsage `json:"usage,omitempty"`
}

// NewApiV1JobJobIdGet200ResponseMeta instantiates a new ApiV1JobJobIdGet200ResponseMeta object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1JobJobIdGet200ResponseMeta() *ApiV1JobJobIdGet200ResponseMeta {
	this := ApiV1JobJobIdGet200ResponseMeta{}
	return &this
}

// NewApiV1JobJobIdGet200ResponseMetaWithDefaults instantiates a new ApiV1JobJobIdGet200ResponseMeta object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1JobJobIdGet200ResponseMetaWithDefaults() *ApiV1JobJobIdGet200ResponseMeta {
	this := ApiV1JobJobIdGet200ResponseMeta{}
	return &this
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetCreatedAt() time.Time {
	if o == nil || IsNil(o.CreatedAt) {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.CreatedAt) {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) HasCreatedAt() bool {
	if o != nil && !IsNil(o.CreatedAt) {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *ApiV1JobJobIdGet200ResponseMeta) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetStartedAt returns the StartedAt field value if set, zero value otherwise.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetStartedAt() time.Time {
	if o == nil || IsNil(o.StartedAt) {
		var ret time.Time
		return ret
	}
	return *o.StartedAt
}

// GetStartedAtOk returns a tuple with the StartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetStartedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.StartedAt) {
		return nil, false
	}
	return o.StartedAt, true
}

// HasStartedAt returns a boolean if a field has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) HasStartedAt() bool {
	if o != nil && !IsNil(o.StartedAt) {
		return true
	}

	return false
}

// SetStartedAt gets a reference to the given time.Time and assigns it to the StartedAt field.
func (o *ApiV1JobJobIdGet200ResponseMeta) SetStartedAt(v time.Time) {
	o.StartedAt = &v
}

// GetEndedAt returns the EndedAt field value if set, zero value otherwise.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetEndedAt() time.Time {
	if o == nil || IsNil(o.EndedAt) {
		var ret time.Time
		return ret
	}
	return *o.EndedAt
}

// GetEndedAtOk returns a tuple with the EndedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetEndedAtOk() (*time.Time, bool) {
	if o == nil || IsNil(o.EndedAt) {
		return nil, false
	}
	return o.EndedAt, true
}

// HasEndedAt returns a boolean if a field has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) HasEndedAt() bool {
	if o != nil && !IsNil(o.EndedAt) {
		return true
	}

	return false
}

// SetEndedAt gets a reference to the given time.Time and assigns it to the EndedAt field.
func (o *ApiV1JobJobIdGet200ResponseMeta) SetEndedAt(v time.Time) {
	o.EndedAt = &v
}

// GetUsage returns the Usage field value if set, zero value otherwise.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetUsage() ApiV1DiffusionPost200ResponseMetaUsage {
	if o == nil || IsNil(o.Usage) {
		var ret ApiV1DiffusionPost200ResponseMetaUsage
		return ret
	}
	return *o.Usage
}

// GetUsageOk returns a tuple with the Usage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) GetUsageOk() (*ApiV1DiffusionPost200ResponseMetaUsage, bool) {
	if o == nil || IsNil(o.Usage) {
		return nil, false
	}
	return o.Usage, true
}

// HasUsage returns a boolean if a field has been set.
func (o *ApiV1JobJobIdGet200ResponseMeta) HasUsage() bool {
	if o != nil && !IsNil(o.Usage) {
		return true
	}

	return false
}

// SetUsage gets a reference to the given ApiV1DiffusionPost200ResponseMetaUsage and assigns it to the Usage field.
func (o *ApiV1JobJobIdGet200ResponseMeta) SetUsage(v ApiV1DiffusionPost200ResponseMetaUsage) {
	o.Usage = &v
}

func (o ApiV1JobJobIdGet200ResponseMeta) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1JobJobIdGet200ResponseMeta) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.CreatedAt) {
		toSerialize["created_at"] = o.CreatedAt
	}
	if !IsNil(o.StartedAt) {
		toSerialize["started_at"] = o.StartedAt
	}
	if !IsNil(o.EndedAt) {
		toSerialize["ended_at"] = o.EndedAt
	}
	if !IsNil(o.Usage) {
		toSerialize["usage"] = o.Usage
	}
	return toSerialize, nil
}

type NullableApiV1JobJobIdGet200ResponseMeta struct {
	value *ApiV1JobJobIdGet200ResponseMeta
	isSet bool
}

func (v NullableApiV1JobJobIdGet200ResponseMeta) Get() *ApiV1JobJobIdGet200ResponseMeta {
	return v.value
}

func (v *NullableApiV1JobJobIdGet200ResponseMeta) Set(val *ApiV1JobJobIdGet200ResponseMeta) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1JobJobIdGet200ResponseMeta) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1JobJobIdGet200ResponseMeta) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1JobJobIdGet200ResponseMeta(val *ApiV1JobJobIdGet200ResponseMeta) *NullableApiV1JobJobIdGet200ResponseMeta {
	return &NullableApiV1JobJobIdGet200ResponseMeta{value: val, isSet: true}
}

func (v NullableApiV1JobJobIdGet200ResponseMeta) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1JobJobIdGet200ResponseMeta) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


