/*
Midjourney api-unofficial by Legnext.ai

# **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ApiV1DiffusionPost200ResponseConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ApiV1DiffusionPost200ResponseConfig{}

// ApiV1DiffusionPost200ResponseConfig struct for ApiV1DiffusionPost200ResponseConfig
type ApiV1DiffusionPost200ResponseConfig struct {
	ServiceMode *string `json:"service_mode,omitempty"`
	WebhookConfig *ApiV1DiffusionPost200ResponseConfigWebhookConfig `json:"webhook_config,omitempty"`
}

// NewApiV1DiffusionPost200ResponseConfig instantiates a new ApiV1DiffusionPost200ResponseConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiV1DiffusionPost200ResponseConfig() *ApiV1DiffusionPost200ResponseConfig {
	this := ApiV1DiffusionPost200ResponseConfig{}
	return &this
}

// NewApiV1DiffusionPost200ResponseConfigWithDefaults instantiates a new ApiV1DiffusionPost200ResponseConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiV1DiffusionPost200ResponseConfigWithDefaults() *ApiV1DiffusionPost200ResponseConfig {
	this := ApiV1DiffusionPost200ResponseConfig{}
	return &this
}

// GetServiceMode returns the ServiceMode field value if set, zero value otherwise.
func (o *ApiV1DiffusionPost200ResponseConfig) GetServiceMode() string {
	if o == nil || IsNil(o.ServiceMode) {
		var ret string
		return ret
	}
	return *o.ServiceMode
}

// GetServiceModeOk returns a tuple with the ServiceMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1DiffusionPost200ResponseConfig) GetServiceModeOk() (*string, bool) {
	if o == nil || IsNil(o.ServiceMode) {
		return nil, false
	}
	return o.ServiceMode, true
}

// HasServiceMode returns a boolean if a field has been set.
func (o *ApiV1DiffusionPost200ResponseConfig) HasServiceMode() bool {
	if o != nil && !IsNil(o.ServiceMode) {
		return true
	}

	return false
}

// SetServiceMode gets a reference to the given string and assigns it to the ServiceMode field.
func (o *ApiV1DiffusionPost200ResponseConfig) SetServiceMode(v string) {
	o.ServiceMode = &v
}

// GetWebhookConfig returns the WebhookConfig field value if set, zero value otherwise.
func (o *ApiV1DiffusionPost200ResponseConfig) GetWebhookConfig() ApiV1DiffusionPost200ResponseConfigWebhookConfig {
	if o == nil || IsNil(o.WebhookConfig) {
		var ret ApiV1DiffusionPost200ResponseConfigWebhookConfig
		return ret
	}
	return *o.WebhookConfig
}

// GetWebhookConfigOk returns a tuple with the WebhookConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ApiV1DiffusionPost200ResponseConfig) GetWebhookConfigOk() (*ApiV1DiffusionPost200ResponseConfigWebhookConfig, bool) {
	if o == nil || IsNil(o.WebhookConfig) {
		return nil, false
	}
	return o.WebhookConfig, true
}

// HasWebhookConfig returns a boolean if a field has been set.
func (o *ApiV1DiffusionPost200ResponseConfig) HasWebhookConfig() bool {
	if o != nil && !IsNil(o.WebhookConfig) {
		return true
	}

	return false
}

// SetWebhookConfig gets a reference to the given ApiV1DiffusionPost200ResponseConfigWebhookConfig and assigns it to the WebhookConfig field.
func (o *ApiV1DiffusionPost200ResponseConfig) SetWebhookConfig(v ApiV1DiffusionPost200ResponseConfigWebhookConfig) {
	o.WebhookConfig = &v
}

func (o ApiV1DiffusionPost200ResponseConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ApiV1DiffusionPost200ResponseConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ServiceMode) {
		toSerialize["service_mode"] = o.ServiceMode
	}
	if !IsNil(o.WebhookConfig) {
		toSerialize["webhook_config"] = o.WebhookConfig
	}
	return toSerialize, nil
}

type NullableApiV1DiffusionPost200ResponseConfig struct {
	value *ApiV1DiffusionPost200ResponseConfig
	isSet bool
}

func (v NullableApiV1DiffusionPost200ResponseConfig) Get() *ApiV1DiffusionPost200ResponseConfig {
	return v.value
}

func (v *NullableApiV1DiffusionPost200ResponseConfig) Set(val *ApiV1DiffusionPost200ResponseConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableApiV1DiffusionPost200ResponseConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableApiV1DiffusionPost200ResponseConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiV1DiffusionPost200ResponseConfig(val *ApiV1DiffusionPost200ResponseConfig) *NullableApiV1DiffusionPost200ResponseConfig {
	return &NullableApiV1DiffusionPost200ResponseConfig{value: val, isSet: true}
}

func (v NullableApiV1DiffusionPost200ResponseConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiV1DiffusionPost200ResponseConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


