// <auto-generated>
/*
 * Midjourney api-unofficial by Legnext.ai
 *
 * # **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

#nullable enable

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.ComponentModel.DataAnnotations;
using Org.OpenAPITools.Client;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// ApiV1JobJobIdGet200ResponseError
    /// </summary>
    public partial class ApiV1JobJobIdGet200ResponseError : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ApiV1JobJobIdGet200ResponseError" /> class.
        /// </summary>
        /// <param name="code">code</param>
        /// <param name="rawMessage">rawMessage</param>
        /// <param name="message">message</param>
        /// <param name="detail">detail</param>
        [JsonConstructor]
        public ApiV1JobJobIdGet200ResponseError(Option<int?> code = default, Option<string?> rawMessage = default, Option<string?> message = default, Option<Object?> detail = default)
        {
            CodeOption = code;
            RawMessageOption = rawMessage;
            MessageOption = message;
            DetailOption = detail;
            OnCreated();
        }

        partial void OnCreated();

        /// <summary>
        /// Used to track the state of Code
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<int?> CodeOption { get; private set; }

        /// <summary>
        /// Gets or Sets Code
        /// </summary>
        [JsonPropertyName("code")]
        public int? Code { get { return this.CodeOption; } set { this.CodeOption = new(value); } }

        /// <summary>
        /// Used to track the state of RawMessage
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> RawMessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets RawMessage
        /// </summary>
        [JsonPropertyName("raw_message")]
        public string? RawMessage { get { return this.RawMessageOption; } set { this.RawMessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Message
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<string?> MessageOption { get; private set; }

        /// <summary>
        /// Gets or Sets Message
        /// </summary>
        [JsonPropertyName("message")]
        public string? Message { get { return this.MessageOption; } set { this.MessageOption = new(value); } }

        /// <summary>
        /// Used to track the state of Detail
        /// </summary>
        [JsonIgnore]
        [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)]
        public Option<Object?> DetailOption { get; private set; }

        /// <summary>
        /// Gets or Sets Detail
        /// </summary>
        [JsonPropertyName("detail")]
        public Object? Detail { get { return this.DetailOption; } set { this.DetailOption = new(value); } }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class ApiV1JobJobIdGet200ResponseError {\n");
            sb.Append("  Code: ").Append(Code).Append("\n");
            sb.Append("  RawMessage: ").Append(RawMessage).Append("\n");
            sb.Append("  Message: ").Append(Message).Append("\n");
            sb.Append("  Detail: ").Append(Detail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

    /// <summary>
    /// A Json converter for type <see cref="ApiV1JobJobIdGet200ResponseError" />
    /// </summary>
    public class ApiV1JobJobIdGet200ResponseErrorJsonConverter : JsonConverter<ApiV1JobJobIdGet200ResponseError>
    {
        /// <summary>
        /// Deserializes json to <see cref="ApiV1JobJobIdGet200ResponseError" />
        /// </summary>
        /// <param name="utf8JsonReader"></param>
        /// <param name="typeToConvert"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <returns></returns>
        /// <exception cref="JsonException"></exception>
        public override ApiV1JobJobIdGet200ResponseError Read(ref Utf8JsonReader utf8JsonReader, Type typeToConvert, JsonSerializerOptions jsonSerializerOptions)
        {
            int currentDepth = utf8JsonReader.CurrentDepth;

            if (utf8JsonReader.TokenType != JsonTokenType.StartObject && utf8JsonReader.TokenType != JsonTokenType.StartArray)
                throw new JsonException();

            JsonTokenType startingTokenType = utf8JsonReader.TokenType;

            Option<int?> code = default;
            Option<string?> rawMessage = default;
            Option<string?> message = default;
            Option<Object?> detail = default;

            while (utf8JsonReader.Read())
            {
                if (startingTokenType == JsonTokenType.StartObject && utf8JsonReader.TokenType == JsonTokenType.EndObject && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (startingTokenType == JsonTokenType.StartArray && utf8JsonReader.TokenType == JsonTokenType.EndArray && currentDepth == utf8JsonReader.CurrentDepth)
                    break;

                if (utf8JsonReader.TokenType == JsonTokenType.PropertyName && currentDepth == utf8JsonReader.CurrentDepth - 1)
                {
                    string? localVarJsonPropertyName = utf8JsonReader.GetString();
                    utf8JsonReader.Read();

                    switch (localVarJsonPropertyName)
                    {
                        case "code":
                            code = new Option<int?>(utf8JsonReader.TokenType == JsonTokenType.Null ? (int?)null : utf8JsonReader.GetInt32());
                            break;
                        case "raw_message":
                            rawMessage = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "message":
                            message = new Option<string?>(utf8JsonReader.GetString()!);
                            break;
                        case "detail":
                            detail = new Option<Object?>(JsonSerializer.Deserialize<Object>(ref utf8JsonReader, jsonSerializerOptions));
                            break;
                        default:
                            break;
                    }
                }
            }

            if (code.IsSet && code.Value == null)
                throw new ArgumentNullException(nameof(code), "Property is not nullable for class ApiV1JobJobIdGet200ResponseError.");

            if (rawMessage.IsSet && rawMessage.Value == null)
                throw new ArgumentNullException(nameof(rawMessage), "Property is not nullable for class ApiV1JobJobIdGet200ResponseError.");

            if (message.IsSet && message.Value == null)
                throw new ArgumentNullException(nameof(message), "Property is not nullable for class ApiV1JobJobIdGet200ResponseError.");

            return new ApiV1JobJobIdGet200ResponseError(code, rawMessage, message, detail);
        }

        /// <summary>
        /// Serializes a <see cref="ApiV1JobJobIdGet200ResponseError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1JobJobIdGet200ResponseError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public override void Write(Utf8JsonWriter writer, ApiV1JobJobIdGet200ResponseError apiV1JobJobIdGet200ResponseError, JsonSerializerOptions jsonSerializerOptions)
        {
            writer.WriteStartObject();

            WriteProperties(writer, apiV1JobJobIdGet200ResponseError, jsonSerializerOptions);
            writer.WriteEndObject();
        }

        /// <summary>
        /// Serializes the properties of <see cref="ApiV1JobJobIdGet200ResponseError" />
        /// </summary>
        /// <param name="writer"></param>
        /// <param name="apiV1JobJobIdGet200ResponseError"></param>
        /// <param name="jsonSerializerOptions"></param>
        /// <exception cref="NotImplementedException"></exception>
        public void WriteProperties(Utf8JsonWriter writer, ApiV1JobJobIdGet200ResponseError apiV1JobJobIdGet200ResponseError, JsonSerializerOptions jsonSerializerOptions)
        {
            if (apiV1JobJobIdGet200ResponseError.RawMessageOption.IsSet && apiV1JobJobIdGet200ResponseError.RawMessage == null)
                throw new ArgumentNullException(nameof(apiV1JobJobIdGet200ResponseError.RawMessage), "Property is required for class ApiV1JobJobIdGet200ResponseError.");

            if (apiV1JobJobIdGet200ResponseError.MessageOption.IsSet && apiV1JobJobIdGet200ResponseError.Message == null)
                throw new ArgumentNullException(nameof(apiV1JobJobIdGet200ResponseError.Message), "Property is required for class ApiV1JobJobIdGet200ResponseError.");

            if (apiV1JobJobIdGet200ResponseError.CodeOption.IsSet)
                writer.WriteNumber("code", apiV1JobJobIdGet200ResponseError.CodeOption.Value!.Value);

            if (apiV1JobJobIdGet200ResponseError.RawMessageOption.IsSet)
                writer.WriteString("raw_message", apiV1JobJobIdGet200ResponseError.RawMessage);

            if (apiV1JobJobIdGet200ResponseError.MessageOption.IsSet)
                writer.WriteString("message", apiV1JobJobIdGet200ResponseError.Message);

            if (apiV1JobJobIdGet200ResponseError.DetailOption.IsSet)
                if (apiV1JobJobIdGet200ResponseError.DetailOption.Value != null)
                {
                    writer.WritePropertyName("detail");
                    JsonSerializer.Serialize(writer, apiV1JobJobIdGet200ResponseError.Detail, jsonSerializerOptions);
                }
                else
                    writer.WriteNull("detail");
        }
    }
}
