# coding: utf-8

"""
    Midjourney api-unofficial by Legnext.ai

    # **Legnext.ai Midjourney API: The Ultimate AI Image Generation Toolkit**  Unlock the full creative potential of Midjourney directly within your applications and development workflows using the **Legnext.ai Midjourney API (Unofficial)**. This comprehensive collection offers a ready-to-integrate solution for professional image and video creation, manipulation, and high-fidelity upscaling.  We provide developers with **stable, high-performance API access** to the Midjourney model. Crucially, integrating our service requires **no Midjourney account**, eliminating the hassle of managing official subscriptions or Discord interactions. Our toolkit simplifies the entire text-to-image process, supporting complex prompts, aspect ratio adjustments, and advanced style parameters.  Focus on innovation while we handle the AI infrastructure. Start building scalable, visually stunning applications today with reliable access to the world’s leading generative AI model.

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.api_v1_diffusion_post200_response_config import ApiV1DiffusionPost200ResponseConfig
from openapi_client.models.api_v1_diffusion_post200_response_meta import ApiV1DiffusionPost200ResponseMeta
from openapi_client.models.api_v1_diffusion_post200_response_output import ApiV1DiffusionPost200ResponseOutput
from typing import Optional, Set
from typing_extensions import Self

class ApiV1PanPost200Response(BaseModel):
    """
    ApiV1PanPost200Response
    """ # noqa: E501
    job_id: Optional[StrictStr] = Field(default=None, description="Unique identifier for the created pan job")
    model: Optional[StrictStr] = Field(default=None, description="AI model used (e.g., midjourney)")
    task_type: Optional[StrictStr] = Field(default=None, description="Type of task (e.g., pan)")
    status: Optional[StrictStr] = Field(default=None, description="Initial status (typically 'pending')")
    config: Optional[ApiV1DiffusionPost200ResponseConfig] = None
    output: Optional[ApiV1DiffusionPost200ResponseOutput] = None
    meta: Optional[ApiV1DiffusionPost200ResponseMeta] = None
    __properties: ClassVar[List[str]] = ["job_id", "model", "task_type", "status", "config", "output", "meta"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ApiV1PanPost200Response from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of config
        if self.config:
            _dict['config'] = self.config.to_dict()
        # override the default output from pydantic by calling `to_dict()` of output
        if self.output:
            _dict['output'] = self.output.to_dict()
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict['meta'] = self.meta.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ApiV1PanPost200Response from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "job_id": obj.get("job_id"),
            "model": obj.get("model"),
            "task_type": obj.get("task_type"),
            "status": obj.get("status"),
            "config": ApiV1DiffusionPost200ResponseConfig.from_dict(obj["config"]) if obj.get("config") is not None else None,
            "output": ApiV1DiffusionPost200ResponseOutput.from_dict(obj["output"]) if obj.get("output") is not None else None,
            "meta": ApiV1DiffusionPost200ResponseMeta.from_dict(obj["meta"]) if obj.get("meta") is not None else None
        })
        return _obj


